services:
  chirpstack-mqtt-forwarder:
    build:
      context: .
      dockerfile: Dockerfile-devel
    volumes:
      - ./:/chirpstack-mqtt-forwarder
    environment:
      - TEST_MQTT_BROKER_URL=tcp://mosquitto:1883
    ports:
      - "1700:1700/udp"
    depends_on:
      - mosquitto

  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
    volumes: 
      - ./.docker-compose/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
